; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=vc16 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=VC16I

define void @jt(i16 %in, i16* %out) {
; VC16I-LABEL: jt:
; VC16I:       ; %bb.0: ; %entry
; VC16I-NEXT:    lli a2, 2
; VC16I-NEXT:    cmp a2, a0
; VC16I-NEXT:    blt .LBB0_4
; VC16I-NEXT:  ; %bb.1: ; %entry
; VC16I-NEXT:    cmpi a0, 1
; VC16I-NEXT:    bz .LBB0_7
; VC16I-NEXT:  ; %bb.2: ; %entry
; VC16I-NEXT:    cmpi a0, 2
; VC16I-NEXT:    bnz .LBB0_10
; VC16I-NEXT:  ; %bb.3: ; %bb2
; VC16I-NEXT:    lli a2, 3
; VC16I-NEXT:    j .LBB0_9
; VC16I-NEXT:  .LBB0_4: ; %entry
; VC16I-NEXT:    cmpi a0, 3
; VC16I-NEXT:    bz .LBB0_8
; VC16I-NEXT:  ; %bb.5: ; %entry
; VC16I-NEXT:    cmpi a0, 4
; VC16I-NEXT:    bnz .LBB0_10
; VC16I-NEXT:  ; %bb.6: ; %bb4
; VC16I-NEXT:    lli a2, 1
; VC16I-NEXT:    j .LBB0_9
; VC16I-NEXT:  .LBB0_7: ; %bb1
; VC16I-NEXT:    lli a2, 4
; VC16I-NEXT:    j .LBB0_9
; VC16I-NEXT:  .LBB0_8: ; %bb3
; VC16I-NEXT:    lli a2, 2
; VC16I-NEXT:  .LBB0_9: ; %exit
; VC16I-NEXT:    sw a2, 0(a1)
; VC16I-NEXT:  .LBB0_10: ; %exit
; VC16I-NEXT:    ret
entry:
  switch i16 %in, label %exit [
    i16 1, label %bb1
    i16 2, label %bb2
    i16 3, label %bb3
    i16 4, label %bb4
  ]
bb1:
  store i16 4, i16* %out
  br label %exit
bb2:
  store i16 3, i16* %out
  br label %exit
bb3:
  store i16 2, i16* %out
  br label %exit
bb4:
  store i16 1, i16* %out
  br label %exit
exit:
  ret void
}
