; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=vc16 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=VC16I

; Check indexed and unindexed, sext, zext and anyext loads

define i16 @lb(i8 *%a) nounwind {
; VC16I-LABEL: lb:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lb a2, 0(a0)
; VC16I-NEXT:    lb a0, 1(a0)
; VC16I-NEXT:    slli a0, 8
; VC16I-NEXT:    srai a0, 8
; VC16I-NEXT:    ret
  %1 = getelementptr i8, i8* %a, i16 1
  %2 = load i8, i8* %1
  %3 = sext i8 %2 to i16
  ; the unused load will produce an anyext for selection
  %4 = load volatile i8, i8* %a
  ret i16 %3
}

define i16 @lw(i16 *%a) nounwind {
; VC16I-LABEL: lw:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lw a2, 0(a0)
; VC16I-NEXT:    lw a0, 6(a0)
; VC16I-NEXT:    ret
  %1 = getelementptr i16, i16* %a, i16 3
  %2 = load i16, i16* %1
  %3 = load volatile i16, i16* %a
  ret i16 %2
}

define i16 @lbu(i8 *%a) nounwind {
; VC16I-LABEL: lbu:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lb a2, 0(a0)
; VC16I-NEXT:    lb a0, 4(a0)
; VC16I-NEXT:    add a0, a2
; VC16I-NEXT:    ret
  %1 = getelementptr i8, i8* %a, i16 4
  %2 = load i8, i8* %1
  %3 = zext i8 %2 to i16
  %4 = load volatile i8, i8* %a
  %5 = zext i8 %4 to i16
  %6 = add i16 %3, %5
  ret i16 %6
}


; Check indexed and unindexed stores

define void @sb(i8 *%a, i8 %b) nounwind {
; VC16I-LABEL: sb:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    sb a1, 6(a0)
; VC16I-NEXT:    sb a1, 0(a0)
; VC16I-NEXT:    ret
  store i8 %b, i8* %a
  %1 = getelementptr i8, i8* %a, i16 6
  store i8 %b, i8* %1
  ret void
}

define void @sw(i16 *%a, i16 %b) nounwind {
; VC16I-LABEL: sw:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    sw a1, 16(a0)
; VC16I-NEXT:    sw a1, 0(a0)
; VC16I-NEXT:    ret
  store i16 %b, i16* %a
  %1 = getelementptr i16, i16* %a, i16 8
  store i16 %b, i16* %1
  ret void
}


; Check load and store to an i1 location
define i16 @load_sext_zext_anyext_i1(i1 *%a) nounwind {
; VC16I-LABEL: load_sext_zext_anyext_i1:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lb a2, 0(a0)
; VC16I-NEXT:    lb a2, 1(a0)
; VC16I-NEXT:    lb a0, 2(a0)
; VC16I-NEXT:    sub a0, a2
; VC16I-NEXT:    ret
  ; sextload i1
  %1 = getelementptr i1, i1* %a, i16 1
  %2 = load i1, i1* %1
  %3 = sext i1 %2 to i16
  ; zextload i1
  %4 = getelementptr i1, i1* %a, i16 2
  %5 = load i1, i1* %4
  %6 = zext i1 %5 to i16
  %7 = add i16 %3, %6
  ; extload i1 (anyext). Produced as the load is unused.
  %8 = load volatile i1, i1* %a
  ret i16 %7
}

; Check load and store to a global
@G = global i16 0

define i16 @lw_sw_global(i16 %a) nounwind {
; VC16I-LABEL: lw_sw_global:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lui a1, %hiu(G)
; VC16I-NEXT:    lw a2, %lo(G)(a1)
; VC16I-NEXT:    sw a0, %lo(G)(a1)
; VC16I-NEXT:    lui a1, %hiu(G+18)
; VC16I-NEXT:    lw t0, %lo(G+18)(a1)
; VC16I-NEXT:    sw a0, %lo(G+18)(a1)
; VC16I-NEXT:    mv a0, a2
; VC16I-NEXT:    ret
  %1 = load volatile i16, i16* @G
  store i16 %a, i16* @G
  %2 = getelementptr i16, i16* @G, i16 9
  %3 = load volatile i16, i16* %2
  store i16 %a, i16* %2
  ret i16 %1
}

; Ensure that 1 is added to the high 11 bits if bit 4 of the low part is 1
define i16 @lw_sw_constant(i16 %a) nounwind {
; VC16I-LABEL: lw_sw_constant:
; VC16I:       ; %bb.0:
; VC16I-NEXT:    lui a1, 1035
; VC16I-NEXT:    lw a2, 18(a1)
; VC16I-NEXT:    sw a0, 18(a1)
; VC16I-NEXT:    mv a0, a2
; VC16I-NEXT:    ret
  %1 = inttoptr i16 33138 to i16*
  %2 = load volatile i16, i16* %1
  store i16 %a, i16* %1
  ret i16 %2
}
