; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=vc16 -verify-machineinstrs -debug < %s \
; RUN:   | FileCheck -check-prefix=VC16I %s

define i8* @memset(i8* returned %buffer, i16 %value, i16 %size) {
; VC16I-LABEL: memset:
; VC16I:       ; %bb.0: ; %entry
; VC16I-NEXT:    mv t0, a0
; VC16I-NEXT:    add t0, a2
; VC16I-NEXT:    cmp a0, t0
; VC16I-NEXT:    bc .LBB0_3
; VC16I-NEXT:  ; %bb.1:
; VC16I-NEXT:    mv t0, a0
; VC16I-NEXT:  .LBB0_2: ; %for.body
; VC16I-NEXT:    ; =>This Inner Loop Header: Depth=1
; VC16I-NEXT:    sb a1, 0(t0)
; VC16I-NEXT:    lea a2, a2, -1
; VC16I-NEXT:    cmpi a2, 0
; VC16I-NEXT:    lea t0, t0, 1
; VC16I-NEXT:    bnz .LBB0_2
; VC16I-NEXT:  .LBB0_3: ; %for.cond.cleanup
; VC16I-NEXT:    ret
entry:
  %add.ptr = getelementptr i8, i8* %buffer, i16 %size
  %cmp7 = icmp ugt i8* %add.ptr, %buffer
  br i1 %cmp7, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %conv = trunc i16 %value to i8
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret i8* %buffer

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %cursor.08 = phi i8* [ %buffer, %for.body.lr.ph ], [ %incdec.ptr, %for.body ]
  store i8 %conv, i8* %cursor.08, align 1
  %incdec.ptr = getelementptr inbounds i8, i8* %cursor.08, i16 1
  %exitcond.not = icmp eq i8* %incdec.ptr, %add.ptr
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
